#pragma once

#include "esp_event.h"

extern esp_event_loop_handle_t   ui_event_loop_handle;

ESP_EVENT_DECLARE_BASE(APP_EVENT); 

enum{
    APP_FILE_REFRESH_REQUEST=0x00,
    APP_FILE_REFRESH_RESPONSE,
    APP_MUSIC_PLAY_REQUEST,
    APP_MUSIC_PLAY_RESPONSE,
    APP_MUSIC_PLAY_button_REQUEST,
    APP_MUSIC_PREV_NEXT_REQUEST,
    APP_MUSIC_AUTO_NEXT_REQUEST,
    APP_WIFI_SCAN_START,
    APP_WIFI_SCAN_DONE,
    APP_WIFI_CONNECT_REQUEST,
    APP_WIFI_DISCONNECT_REQUEST,
    APP_WIFI_CLOSE,
    APP_WIFI_CLOSED_DONE,
    APP_WIFI_DISCONNECTED,
    APP_GET_IP,
    APP_SNTP_REQUEST,
    APP_MAIN_STATUS_UPDATE,
    APP_CAMERA_ENTER,
    APP_CAMERA_EXIT,
};

void  ui_event_loop_init(void);
